### ISSUE TITLE
Error `1007` gateway disconnect loop

### ISSUE THREAD

**Issue by R3alCl0ud** [R3alCl0ud/DiscLoader#31]
If you leave a bot running for several days the client will eventually get stuck in a disconnect loop with the gateway, it will always get the close code `1007`.  a quick google search says that close code `1007` is caused by sending an invalid/borked payload to the gateway.

**Comment by prompt-cliffside** [comment]
Throwing this out here as nothing seems in sight- I wonder if the times that it is running on believes it’s running at is confusing the recipient of it and believing it is invalid due to it not having same (or close) times

**Comment by R3alCl0ud** [comment]
I've figured out the cause of this issue. When the client successfully reconnects and resumes a gateway connection, the `lastHeartbeatAck` field of the `Gateway` object is left as `false` causing the client to disconnect from the gateway using the closecode `1007` when it attempts to heartbeat for the first time since reconnecting.

**Comment by R3alCl0ud** [comment]
The fix appears to be working correctly.
