### ISSUE TITLE
.DS_Store still in repository even when it is in .gitignore

### ISSUE THREAD

**Issue by spikespaz** [R3alCl0ud/DiscLoader#33]
Posting as an issue because it is a problem on your side; here's how to fix it.

~~Don't use a mac.~~

*Ehem.*

    git rm --cached .DS_Store
    rm .DS_Store
    git add .DS_Store
    git commit -m "Remove and untrack .DS_Store"
    git push

You get the idea. Make changes as necessary.

Also, I've noticed that some of your commit messages start with past-tense verbs or lowercase letters. I'm only pointing this out because I know you. 😄

**Comment by R3alCl0ud** [comment]
I've removed the `.DS_Store` file from the repository. Btw, I've already added .DS_Store to the `.gitignore` file.
